version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=campagne123
      - DB_NAME=campagnedb

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: campagne123
      MYSQL_DATABASE: campagnedb
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
